"""baseline

Revision ID: 0bd3126639f0
Revises: 
Create Date: 2026-05-05 02:27:02.925713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd3126639f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antibody_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('conjugate_chemistries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fluorophores',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fluor_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('ex_max_nm', sa.Float(), nullable=True),
    sa.Column('em_max_nm', sa.Float(), nullable=True),
    sa.Column('ext_coeff', sa.Float(), nullable=True),
    sa.Column('qy', sa.Float(), nullable=True),
    sa.Column('lifetime_ns', sa.Float(), nullable=True),
    sa.Column('oligomerization', sa.String(), nullable=True),
    sa.Column('switch_type', sa.String(), nullable=True),
    sa.Column('has_spectra', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('instruments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('list_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_type', 'value', name='uq_list_entry')
    )
    op.create_table('microscopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plate_maps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plate_type', sa.String(length=20), nullable=False),
    sa.Column('well_data', sa.Text(), nullable=False),
    sa.Column('legend', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('antibodies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('clone', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('isotype', sa.String(), nullable=True),
    sa.Column('fluorophore_id', sa.String(length=100), nullable=True),
    sa.Column('conjugate', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('catalog_number', sa.String(), nullable=True),
    sa.Column('confirmed_in_stock', sa.Boolean(), nullable=False),
    sa.Column('date_received', sa.String(), nullable=True),
    sa.Column('flow_dilution', sa.String(), nullable=True),
    sa.Column('icc_if_dilution', sa.String(), nullable=True),
    sa.Column('wb_dilution', sa.String(), nullable=True),
    sa.Column('flow_dilution_factor', sa.Integer(), nullable=True),
    sa.Column('icc_if_dilution_factor', sa.Integer(), nullable=True),
    sa.Column('wb_dilution_factor', sa.Integer(), nullable=True),
    sa.Column('reacts_with', sa.Text(), nullable=True),
    sa.Column('storage_temp', sa.String(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('physical_location', sa.String(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['fluorophore_id'], ['fluorophores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'catalog_number', name='uq_antibody_name_catalog')
    )
    op.create_table('dye_labels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label_target', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('fluorophore_id', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('catalog_number', sa.String(), nullable=True),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('flow_dilution', sa.String(), nullable=True),
    sa.Column('icc_if_dilution', sa.String(), nullable=True),
    sa.Column('flow_dilution_factor', sa.Integer(), nullable=True),
    sa.Column('icc_if_dilution_factor', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['fluorophore_id'], ['fluorophores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experiment_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('block_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Float(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['experiment_blocks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fluorophore_spectra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fluorophore_id', sa.String(length=100), nullable=False),
    sa.Column('spectrum_type', sa.String(length=10), nullable=False),
    sa.Column('wavelength_nm', sa.Float(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fluorophore_id'], ['fluorophores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fluorophore_spectra', schema=None) as batch_op:
        batch_op.create_index('ix_fluor_spectra', ['fluorophore_id', 'spectrum_type', 'wavelength_nm'], unique=False)

    op.create_table('if_panels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('panel_type', sa.String(length=3), nullable=False),
    sa.Column('microscope_id', sa.String(length=36), nullable=True),
    sa.Column('view_mode', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['microscope_id'], ['microscopes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.String(length=36), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instrument_views', schema=None) as batch_op:
        batch_op.create_index('ix_instrument_views_instrument_viewed', ['instrument_id', 'viewed_at'], unique=False)

    op.create_table('lasers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instrument_id', sa.String(length=36), nullable=False),
    sa.Column('wavelength_nm', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('microscope_lasers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('microscope_id', sa.String(length=36), nullable=False),
    sa.Column('wavelength_nm', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('excitation_type', sa.String(length=10), nullable=False),
    sa.Column('ex_filter_width', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['microscope_id'], ['microscopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('microscope_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('microscope_id', sa.String(length=36), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['microscope_id'], ['microscopes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('microscope_views', schema=None) as batch_op:
        batch_op.create_index('ix_microscope_views_microscope_viewed', ['microscope_id', 'viewed_at'], unique=False)

    op.create_table('panels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secondary_antibodies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('target_species', sa.String(), nullable=False),
    sa.Column('target_isotype', sa.String(), nullable=True),
    sa.Column('binding_mode', sa.String(length=20), nullable=False),
    sa.Column('target_conjugate', sa.String(), nullable=True),
    sa.Column('fluorophore_id', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('catalog_number', sa.String(), nullable=True),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['fluorophore_id'], ['fluorophores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('antibody_tag_assignments',
    sa.Column('antibody_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['antibody_id'], ['antibodies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['antibody_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('antibody_id', 'tag_id')
    )
    op.create_table('detectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('laser_id', sa.String(length=36), nullable=False),
    sa.Column('filter_midpoint', sa.Integer(), nullable=False),
    sa.Column('filter_width', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['laser_id'], ['lasers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('if_panel_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=False),
    sa.Column('antibody_id', sa.String(length=36), nullable=True),
    sa.Column('dye_label_id', sa.String(length=36), nullable=True),
    sa.Column('staining_mode', sa.String(length=10), nullable=False),
    sa.Column('secondary_antibody_id', sa.String(length=36), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('dilution_override', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['antibody_id'], ['antibodies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dye_label_id'], ['dye_labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['panel_id'], ['if_panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secondary_antibody_id'], ['secondary_antibodies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id', 'antibody_id', name='uq_if_panel_target')
    )
    op.create_table('microscope_filters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('laser_id', sa.String(length=36), nullable=False),
    sa.Column('filter_midpoint', sa.Integer(), nullable=False),
    sa.Column('filter_width', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['laser_id'], ['microscope_lasers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=False),
    sa.Column('antibody_id', sa.String(length=36), nullable=True),
    sa.Column('dye_label_id', sa.String(length=36), nullable=True),
    sa.Column('staining_mode', sa.String(length=10), nullable=False),
    sa.Column('secondary_antibody_id', sa.String(length=36), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['antibody_id'], ['antibodies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dye_label_id'], ['dye_labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secondary_antibody_id'], ['secondary_antibodies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id', 'antibody_id', name='uq_panel_target')
    )
    op.create_table('if_panel_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=False),
    sa.Column('antibody_id', sa.String(length=36), nullable=True),
    sa.Column('dye_label_id', sa.String(length=36), nullable=True),
    sa.Column('fluorophore_id', sa.String(length=100), nullable=False),
    sa.Column('filter_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['antibody_id'], ['antibodies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dye_label_id'], ['dye_labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filter_id'], ['microscope_filters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fluorophore_id'], ['fluorophores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['panel_id'], ['if_panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('panel_id', sa.String(length=36), nullable=False),
    sa.Column('antibody_id', sa.String(length=36), nullable=True),
    sa.Column('dye_label_id', sa.String(length=36), nullable=True),
    sa.Column('fluorophore_id', sa.String(length=100), nullable=False),
    sa.Column('detector_id', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['antibody_id'], ['antibodies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detector_id'], ['detectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dye_label_id'], ['dye_labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fluorophore_id'], ['fluorophores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id', 'detector_id', name='uq_panel_detector')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panel_assignments')
    op.drop_table('if_panel_assignments')
    op.drop_table('panel_targets')
    op.drop_table('microscope_filters')
    op.drop_table('if_panel_targets')
    op.drop_table('detectors')
    op.drop_table('antibody_tag_assignments')
    op.drop_table('secondary_antibodies')
    op.drop_table('panels')
    with op.batch_alter_table('microscope_views', schema=None) as batch_op:
        batch_op.drop_index('ix_microscope_views_microscope_viewed')

    op.drop_table('microscope_views')
    op.drop_table('microscope_lasers')
    op.drop_table('lasers')
    with op.batch_alter_table('instrument_views', schema=None) as batch_op:
        batch_op.drop_index('ix_instrument_views_instrument_viewed')

    op.drop_table('instrument_views')
    op.drop_table('if_panels')
    with op.batch_alter_table('fluorophore_spectra', schema=None) as batch_op:
        batch_op.drop_index('ix_fluor_spectra')

    op.drop_table('fluorophore_spectra')
    op.drop_table('experiment_blocks')
    op.drop_table('dye_labels')
    op.drop_table('antibodies')
    op.drop_table('user_preferences')
    op.drop_table('plate_maps')
    op.drop_table('microscopes')
    op.drop_table('list_entries')
    op.drop_table('instruments')
    op.drop_table('fluorophores')
    op.drop_table('experiments')
    op.drop_table('conjugate_chemistries')
    op.drop_table('antibody_tags')
    # ### end Alembic commands ###
