#!/usr/bin/env bash
# generate_index.sh — orchestrate backend + frontend index generation.
#
# Concatenates the two partial index files into a single CODEBASE_INDEX.md
# at the repo root. Pass --check to verify freshness without writing.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

CHECK=""
if [[ "${1:-}" == "--check" ]]; then
    CHECK="--check"
fi

BACKEND_OUT="CODEBASE_INDEX.backend.md"
FRONTEND_OUT="CODEBASE_INDEX.frontend.md"
FINAL_OUT="CODEBASE_INDEX.md"

python3 tools/generate_backend_index.py \
    --models backend/models.py \
    --schemas backend/schemas.py \
    --main backend/main.py \
    --routers-dir backend/routers \
    --out "$BACKEND_OUT" \
    $CHECK

node tools/generate_frontend_index.mjs \
    --tsconfig frontend/tsconfig.json \
    --root frontend/src \
    --out "$FRONTEND_OUT" \
    $CHECK

# Combine. The check mode already exited non-zero above if either was stale;
# we still rebuild the combined file from the partials in non-check mode.
if [[ -z "$CHECK" ]]; then
    {
        echo "<!-- AUTO-GENERATED by tools/generate_index.sh. Do not edit. -->"
        echo "<!-- Regenerate: \`make index\`. Check freshness: \`make check-index\`. -->"
        echo ""
        cat "$BACKEND_OUT"
        echo ""
        cat "$FRONTEND_OUT"
    } > "$FINAL_OUT"
    echo "Wrote $FINAL_OUT"
fi
